#name: try { ... } catch (Exception e) { ... }
# --
try {
    $0
}
catch (${1:Exception} ${2:e}) {
    
}